version: '3.9'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  simulator:
    build:
      context: ./Simulator
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./Simulator:/app

  blockchain:
    build:
      context: ./smart_contract
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
    volumes:
      - ./smart_contract:/app
